# [generated]
# by = { compiler = "ecoscope-workflows-core", version = "9999" }
# from-spec-sha256 = "224406132661acaaeeb8cedc6cb05519ede1e8fa60732c93ad1407f30539d898"

[project]
name = "ecoscope-workflows-mode-mapvalues-workflow"
channels = [
    "file:///tmp/ecoscope-workflows/release/artifacts/",
    "https://repo.prefix.dev/ecoscope-workflows/",
    "conda-forge",
]
platforms = [
    "linux-64",
    "linux-aarch64",
    "osx-arm64",
]

[dependencies.fastapi]
version = "*"

[dependencies.httpx]
version = "*"

[dependencies.uvicorn]
version = "*"

[dependencies."ruamel.yaml"]
version = "*"

[dependencies.ecoscope-workflows-core]
version = "*"
channel = "file:///tmp/ecoscope-workflows/release/artifacts/"

[dependencies.ecoscope-workflows-ext-ecoscope]
version = "*"
channel = "file:///tmp/ecoscope-workflows/release/artifacts/"

[feature.test.dependencies.pytest]
version = "*"

[feature.test.tasks]
test-all = "python -m pytest -v tests"
test-app-async-mock-io = "python -m pytest -v tests/test_app.py -k 'async and mock-io'"
test-app-sequential-mock-io = "python -m pytest -v tests/test_app.py -k 'sequential and mock-io'"
test-cli-async-mock-io = "python -m pytest -v tests/test_cli.py -k 'async and mock-io'"
test-cli-sequential-mock-io = "python -m pytest -v tests/test_cli.py -k 'sequential and mock-io'"

[environments.default]
features = []
solve-group = "default"

[environments.test]
features = [
    "test",
]
solve-group = "default"

[tasks]
docker-build = "mkdir -p .tmp/ecoscope-workflows/release/artifacts/\n&& cp -r /tmp/ecoscope-workflows/release/artifacts/* .tmp/ecoscope-workflows/release/artifacts/\n&& docker buildx build -t ecoscope-workflows-mode-mapvalues-workflow .\n"

[pypi-dependencies.ecoscope-workflows-mode-mapvalues-workflow]
path = "."
editable = true
