version: 2
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"
  commands:
    - pip install ".[lithops,visualize]"
    - pip install pdoc3
    - pdoc --html --output-dir $READTHEDOCS_OUTPUT/html/ ecoscope_workflows
    - echo "<!DOCTYPE html><html><head><meta http-equiv=\"refresh\" content=\"0; url=ecoscope_workflows/index.html\"></head><body><p>If you are not redirected, <a href=\"ecoscope_workflows/index.html\">click here</a>.</p></body></html>" > $READTHEDOCS_OUTPUT/html/index.html
