[project]
name = "ecoscope-workflows-manage"
channels = [
    "https://prefix.dev/ecoscope-workflows",
    "conda-forge",
]
platforms = ["linux-64", "linux-aarch64", "osx-arm64"]

[tasks]
recompile-mode-map = { cmd = "./recompile.sh mode-map" }
recompile-mode-mapvalues = { cmd = "./recompile.sh mode-mapvalues" }
recompile-patrol-events = { cmd = "./recompile.sh patrol-events" }
recompile-patrols = { cmd = "./recompile.sh patrols" }
recompile-subject-tracking = { cmd = "./recompile.sh subject-tracking" }

recompile-all = { cmd = "echo 'all examples recompiled'", depends-on = [
    "recompile-mode-map",
    "recompile-mode-mapvalues",
    "recompile-patrol-events",
    "recompile-patrols",
    "recompile-subject-tracking",
] }


[feature.conda-dist]
dependencies = { rattler-build = "*" }
# tasks to:
#  - manually build the vendor packages from the recipes; and then
#  - manually push built packages to the channel (requires prefix api key env var)
# these are not run in ci. if `vendor-version-check check` fails, use these to update the vendor packages.
# note: in this case, the recipes themselves likely need to be manually updated before build/push.
tasks = { build-release = "publish/build.sh release"}

[environments]
default = { solve-group = "default" }
conda-dist = { features = ["conda-dist"], solve-group = "conda-dist", no-default-feature = true }
