[project]
name = "ecoscope-workflows-dev"
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64", "osx-arm64"]

[dependencies]
rattler-build = "*"

[tasks]
rmrf-release-artifacts = { cmd = "rm -rf /tmp/ecoscope-workflows/release/artifacts" }
build-vendor = { cmd = "./publish/build.sh vendor", inputs = ["publish/recipes/vendor/*.yaml"], depends-on = ["rmrf-release-artifacts"] }
build-release = { cmd = "./publish/build.sh release", depends-on = ["build-vendor"] }

recompile-mode-map = { cmd = "./dev/recompile.sh mode-map", depends-on = ["build-release"] }
recompile-mode-mapvalues = { cmd = "./dev/recompile.sh mode-mapvalues", depends-on = ["build-release"] }
recompile-patrol-events = { cmd = "./dev/recompile.sh patrol-events", depends-on = ["build-release"] }
recompile-patrols = { cmd = "./dev/recompile.sh patrols", depends-on = ["build-release"] }
recompile-subject-tracking = { cmd = "./dev/recompile.sh subject-tracking", depends-on = ["build-release"] }

recompile-all = { cmd = "echo 'all examples recompiled'", depends-on = [
    "recompile-mode-map",
    "recompile-mode-mapvalues",
    "recompile-patrol-events",
    "recompile-patrols",
    "recompile-subject-tracking",
] }
