id: mapvalues_example
workflow:
  # ----------------------------------------------------------------------
  # Mapping over a groups split from a single data source, which are keyed
  # ----------------------------------------------------------------------
  # Step 1 - Fetching a single data source
  - name: Get Observations
    id: obs
    task: get_subjectgroup_observations
  # Step 2 - Setting the groupers
  - name: Set Groupers
    id: groupers
    task: set_groupers
  # Step 3 - Splitting the data source into groups
  - name: Split Observations
    id: split_obs
    task: split_groups
    partial:
      df: ${{ workflow.obs.return }}
      groupers: ${{ workflow.groupers.return }}
  # Step 4 - Mapping over the groups
  - name: Create EcoMap For Each Group
    id: ecomaps
    task: draw_ecomap
    mapvalues:
      argnames: "geodataframe"
      argvalues: ${{ workflow.split_obs.return }}
  # Step 5 - Persisting the EcoMaps
  - name: Persist EcoMaps
    id: ecomaps_persist
    task: persist_text
    partial:
      root_path: ${{ env.ECOSCOPE_WORKFLOWS_RESULTS }}
    mapvalues:
      argnames: "text"
      argvalues: ${{ workflow.ecomaps.return }}
  # Step 6 - Creating Widgets for Each EcoMap
  - name: Create EcoMap Widgets
    id: ecomap_widgets
    task: create_map_widget_single_view
    map:
      argnames: ["view", data"]
      argvalues: ${{ workflow.ecomaps_persist.return }}
