FROM mambaorg/micromamba:bullseye-slim AS only_deps

# todo: .gitignore/cache
ARG CHANNEL_MOUNT=.rattler-build/artifacts

USER root
RUN micromamba create -p /env
RUN --mount=type=bind,source=$CHANNEL_MOUNT,target=/opt/channel-mount \
    --mount=type=cache,target=/opt/conda/pkgs \
    micromamba install -p /env \
    ecoscope-workflows \
    -c file:///opt/channel-mount \
    -c conda-forge \
    --only-deps \
    --yes
USER $MAMBA_USER
