FROM mambaorg/micromamba:bullseye-slim AS build

ENV INSTALL_PKG=ecoscope-workflows
ENV CHANNEL_MOUNT=/opt/channel-mount
ENV PKGCACHE_MOUNT=/opt/pkg-cache

# The idea being that we are just trying to create a tarball of the pkg cache; remember
# that when we build the next image, use `--offline` to ensure that the tarball is used
CMD micromamba install ${INSTALL_PKG} \
    -c file://${CHANNEL_MOUNT} \
    -c conda-forge \
    --download-only \
    --only-deps \
    -vvv \
    --yes
    # && tar -czvf ${OUTDIR_MOUNT}/${hash-of-local-recipes}.tar.gz /opt/conda/pkgs
