[project]
name = "ecoscope-workflows-mode-map-workflow"
channels = [
    "file:///tmp/ecoscope-workflows/release/artifacts/",
    "https://repo.prefix.dev/ecoscope-workflows/",
    "conda-forge",
]
platforms = [
    "linux-64",
    "linux-aarch64",
    "osx-arm64",
]

[dependencies.ecoscope-workflows-core]
version = "*"
channel = "file:///tmp/ecoscope-workflows/release/artifacts/"

[dependencies.ecoscope-workflows-ext-ecoscope]
version = "*"
channel = "file:///tmp/ecoscope-workflows/release/artifacts/"

[feature.app.dependencies.fastapi]
version = "*"

[feature.app.dependencies.httpx]
version = "*"

[feature.app.dependencies.uvicorn]
version = "*"

[feature.app.dependencies."ruamel.yaml"]
version = "*"

[feature.app.tasks]

[feature.test.dependencies.pytest]
version = "*"

[feature.test.tasks]
test-all = "python -m pytest -v tests"
test-app-async-mock-io = "python -m pytest -v tests/test_app.py -k 'async and mock-io'"
test-app-sequential-mock-io = "python -m pytest -v tests/test_app.py -k 'sequential and mock-io'"
test-cli-async-mock-io = "python -m pytest -v tests/test_cli.py -k 'async and mock-io'"
test-cli-sequential-mock-io = "python -m pytest -v tests/test_cli.py -k 'sequential and mock-io'"

[environments.default]
features = []
solve-group = "default"

[environments.app]
features = [
    "app",
]
solve-group = "app"

[environments.test]
features = [
    "test",
]
solve-group = "default"

[environments.test-app]
features = [
    "test",
    "app",
]
solve-group = "default"

[tasks]
docker-build = "mkdir -p .tmp/ecoscope-workflows/release/artifacts/\n&& cp -r /tmp/ecoscope-workflows/release/artifacts/* .tmp/ecoscope-workflows/release/artifacts/\n&& docker buildx build -t ecoscope-workflows-mode-map-workflow .\n"

[pypi-dependencies.ecoscope-workflows-mode-map-workflow]
path = "."
editable = true
