apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver-node-port
spec:
  type: NodePort
  selector:
    tier: airflow
    component: webserver
  ports:
  - protocol: TCP
    port: 6004
    targetPort: 8080
    nodePort: 30007  # https://kubernetes.io/docs/concepts/services-networking/service/#nodeport-custom-port
