[project]
name = "mode-map"
channels = [
    "file:///tmp/ecoscope-workflows/release/artifacts/",
    "https://prefix.dev/ecoscope-workflows",
    "conda-forge",
]
platforms = ["linux-64", "linux-aarch64", "osx-arm64"]

[dependencies]
ecoscope-workflows-core = { version = "*", channel = "file:///tmp/ecoscope-workflows/release/artifacts/" }
ecoscope-workflows-ext-ecoscope = {version = "*", channel = "file:///tmp/ecoscope-workflows/release/artifacts/" }

[feature.test.dependencies]
pytest = "*"
[feature.test.tasks]
# test-async-local = "pytest test -k async"
# test-async-remote = "pytest test -k async"
test-sequential-mock-io = "pytest tests -k 'sequential and mock-io'"

# todo: support build; push; deploy; run; test; etc. tasks
# [feature.docker.tasks]
# build-base = "docker build -t mode-map-base -f Dockerfile.base ."
# build-runner = "docker build -t mode-map-runner -f Dockerfile.runner ."
# build-deploy-worker = "docker build -t mode-map-worker -f Dockerfile.worker ."

[environments]
default = { solve-group = "default" }
test = { features = ["test"], solve-group = "default" }
