[project]
name = "mode-map"
channels = [
    "file:///tmp/ecoscope-workflows/release/artifacts/",
    "https://prefix.dev/ecoscope-workflows",
    "conda-forge",
]
platforms = ["linux-64", "linux-aarch64", "osx-arm64"]

[dependencies]
ecoscope-workflows-core = { version = "*", channel = "file:///tmp/ecoscope-workflows/release/artifacts/" }
ecoscope-workflows-ext-ecoscope = {version = "*", channel = "file:///tmp/ecoscope-workflows/release/artifacts/" }

[feature.test.dependencies]
pytest = "*"
[feature.test.tasks]
test-async-local-mock-io = "python -m pytest tests -k 'async and mock-io'"
test-sequential-local-mock-io = "python -m pytest tests -k 'sequential and mock-io'"

[environments]
default = { solve-group = "default" }
test = { features = ["test"], solve-group = "default" }
