name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

jobs:
  test-core:
    steps:
      - uses: actions/checkout@v4
      - name: Install pixi
        run: |
          curl -fsSL https://pixi.sh/install.sh | bash

      - name: Install environment
        run: |
          pixi install --environment=test src/ecoscope_workflows/core

      - name: Test ecoscope_workflows.core
        run: |
          pixi run - pytest src/titiler/core --cov=titiler.core --cov-report=xml --cov-append --cov-report=term-missing
