name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

jobs:
  # vendor-version-check:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Install pixi
  #       run: curl -fsSL https://pixi.sh/install.sh | bash && echo "$HOME/.pixi/bin" >> $GITHUB_PATH
  #     - name: Check vendor versions
  #       run: pixi run --locked --environment vendor-version-check check

  # mypy:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       python-version: ["310", "311", "312"]
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Install pixi
  #       run: curl -fsSL https://pixi.sh/install.sh | bash && echo "$HOME/.pixi/bin" >> $GITHUB_PATH
  #     - name: Mypy
  #       run: |
  #         pixi run --locked --environment mypy-py${{ matrix.python-version }} mypy

  # doctest:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       python-version: ["310", "311", "312"]
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Install pixi
  #       run: curl -fsSL https://pixi.sh/install.sh | bash && echo "$HOME/.pixi/bin" >> $GITHUB_PATH
  #     - name: Test
  #       run: |
  #         pixi run --locked --environment test-all-py${{ matrix.python-version }} \
  #         pytest -v ecoscope_workflows/ --doctest-modules --ignore=ecoscope_workflows/visualize.py

  test-core:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["310", "311", "312"]
    steps:
      - uses: actions/checkout@v4
      - name: Install pixi
        run: curl -fsSL https://pixi.sh/install.sh | bash && echo "$HOME/.pixi/bin" >> $GITHUB_PATH
      - name: Test
        run: |
          pixi run \
          --manifest-path src/ecoscope-workflows/core/pyproject.toml \
          --locked --environment test-py312 \
          pytest src/ecoscope-workflows/core/tests/tasks -vx

  # test-tasks-not-io:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       python-version: ["310", "311", "312"]
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Install pixi
  #       run: curl -fsSL https://pixi.sh/install.sh | bash && echo "$HOME/.pixi/bin" >> $GITHUB_PATH
  #     - name: Test
  #       run: pixi run --locked --environment test-all-py${{ matrix.python-version }} pytest -v tests/tasks -m "not io"

  # test-tasks-io:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       python-version: ["310", "311", "312"]
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Install pixi
  #       run: curl -fsSL https://pixi.sh/install.sh | bash && echo "$HOME/.pixi/bin" >> $GITHUB_PATH
  #     - name: Test
  #       env:
  #         EARTHRANGER_SERVER: ${{ secrets.EARTHRANGER_SERVER }}
  #         EARTHRANGER_USERNAME: ${{ secrets.EARTHRANGER_USERNAME }}
  #         EARTHRANGER_PASSWORD: ${{ secrets.EARTHRANGER_PASSWORD }}
  #       run: pixi run --locked --environment test-all-py${{ matrix.python-version }} pytest -v tests/tasks -m "io"
