name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

jobs:
  test-core-default-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pixi
        run: |
          curl -fsSL https://pixi.sh/install.sh | bash
          echo "$HOME/.pixi/bin" >> $GITHUB_PATH
      - name: Test ecoscope_workflows.core
        run: |
          pixi run --locked \
          --environment test-default \
          --manifest-path src/ecoscope-workflows/core/pyproject.toml \
          pytest -v src/ecoscope-workflows/core/tests
