name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

jobs:
  test-core:
    steps:
      - uses: actions/checkout@v4
      - name: Install pixi
        run: |
          curl -fsSL https://pixi.sh/install.sh | bash

      - name: Install environment
        run: |
          pixi install --environment=test-all --manifest-path src/ecoscope-workflows/core/pyproject.toml

      - name: Test ecoscope_workflows.core
        run: |
          pixi run --environment test-all \
          --manifest-path src/ecoscope-workflows/core/pyproject.toml \
          pytest -v src/ecoscope-workflows/core
