name: Examples

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        execution-mode: ["sequential", "async-local", "async-cloudrun"]
        compilation-spec: [
          "mode-map",
          # "mode-mapvalues",
          # "patrol_events",
          # "patrol_workflow",
          # "subject_tracking",
        ]
    steps:
      - uses: actions/checkout@v4
      - name: Install pixi
        run: curl -fsSL https://pixi.sh/install.sh | bash && echo "$HOME/.pixi/bin" >> $GITHUB_PATH
      - name: Test
        working-directory: ./examples/${{ matrix.compilation-spec }}/build
        # note: to lock the environment, from this working directory (*/build), run:
        # ```
        # SETUPTOOLS_SCM_PRETEND_VERSION=$(cat src/ecoscope-workflows/ecoscope_workflows/_version.py | awk -F"'" '{print $2}')\
        # pixi install -a --manifest-path pixi.toml
        # ```
        # then we can run the tests based on the locked environment, i.e.:
        run: |
          pixi run --locked --manifest-path pixi.toml -e test test-${{ matrix.execution-mode }}
