name: Examples

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        script: [
          "sequential",
          # "async-local",
          # "async-cloudrun",
        ]
        compilation-spec: [
          "mode-map",
          # "mode-mapvalues",
          # "patrol_events",
          # "patrol_workflow",
          # "subject_tracking",
        ]
    steps:
      - uses: actions/checkout@v4
      - name: Install pixi
        run: curl -fsSL https://pixi.sh/install.sh | bash && echo "$HOME/.pixi/bin" >> $GITHUB_PATH
      - name: Test
        working-directory: ./examples/${{ matrix.compilation-spec }}/workflow
        run: |
          pixi run --locked --manifest-path pixi.toml -e test \
          test-${{ matrix.script }}-mock-io --case test1
