name: Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - uses: actions/cache@v4
      id: restore-cache
      with:
        key: "venv-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml') }}"
        path: |
          .venv/

    # If python patch version changes, or pyproject.toml gets updated,
    # the cache lookup will miss, and the  venv needs to be recreated.
    - name: If no cache hit, recreate venv
      if: "steps.restore-cache.outputs.cache-hit == false"
      run: |
        python -m venv .venv
        .venv/bin/python -m pip install --upgrade pip
        .venv/bin/python -m pip install -e ".[test]"

    - name: Lint
      run: |
        python -m pip install pre-commit
        pre-commit install
        pre-commit run --all-files

    # - name: Upload Coverage to Codecov
    #   uses: codecov/codecov-action@v2
