name: Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip"

    - name: Install dependencies, our package, and pre-commit
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e ".[test]"
        python -m pip install pre-commit

    - name: Lint
      run: |
        pre-commit install
        pre-commit run --all-files

    # - name: Upload Coverage to Codecov
    #   uses: codecov/codecov-action@v2
