name: Test Rattler Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

jobs:
  set-deps-hash:
    runs-on: ubuntu-latest
    outputs:
      deps-hash: ${{ steps.set-hash.outputs.deps-hash }}
    steps:
      - uses: actions/checkout@v4
      - name: Set dependency files hash
        id: set-hash
        run: |
          echo "deps-hash=${{ hashFiles('.rattler-build/recipes/**.yaml', '.rattler-build/build.sh', 'pyproject.toml') }}" >> $GITHUB_OUTPUT
  build-conda-channel:
    runs-on: ubuntu-latest
    needs: set-deps-hash
    steps:
      - uses: actions/checkout@v4
      - name: Setup micromamba env for rattler build
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: rattler
          init-shell: bash
      - uses: actions/cache@v4
        id: restore-cache
        with:
          path: .rattler-build/artifacts/  # this path is gitignored, so it won't be in the checkout, only the cache
          # todo: use the same cache key to also skip no-deps build in subsequent job if cache hit
          key: ${{ runner.os }}-${{ needs.set-deps-hash.outputs.deps-hash }}
      - name: Install rattler-build & build artifacts (i.e. local conda channel)
        if: steps.restore-cache.outputs.cache-hit != 'true'
        shell: bash -leo pipefail {0}
        run: |
          micromamba install -c conda-forge rattler-build --yes
          chmod +x .rattler-build/build.sh
          ./.rattler-build/build.sh
      - name: Upload conda channel
        uses: actions/upload-artifact@v4
        with:
          name: rattler-artifacts
          path: |
            .rattler-build/artifacts/
            !.rattler-build/artifacts/bld
            !.rattler-build/artifacts/src_cache
          if-no-files-found: error
          compression-level: 0

  build-only-deps:
    runs-on: ubuntu-latest
    needs:
      - set-deps-hash
      - build-conda-channel
    outputs:
      image-tag: ${{ steps.set-tag.outputs.image-tag }}
    steps:
      - name: Download conda channel
        uses: actions/download-artifact@v4
        with:
          name: rattler-artifacts
          path: tmp/conda-channel
      - name: Log conda channel contents
        run: ls -lR tmp/conda-channel
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set only deps image tag on env and output for downstream jobs
        id: set-tag
        run: |  # note: tag is based on deps hash, so we can avoid rebuilding if deps haven't changed
          export NAME=wildlife-dynamics/ecoscope-workflows-only-deps
          export SHORT_DEPS_HASH=$(${{ needs.set-deps-hash.outputs.deps-hash }} | cut -c1-7)
          export TAG=$SHORT_DEPS_HASH
          echo "IMAGE_TAG=ghcr.io/$NAME:$TAG" >> $GITHUB_ENV
          echo "image-tag=ghcr.io/$NAME:$TAG" >> $GITHUB_OUTPUT
      # TODO: if cache hit, just pull the image
      - name: Build and push only deps image
        run: |
          docker buildx build \
          --tag ${{ env.IMAGE_TAG }} \
          --platform=linux/amd64 \
          --file docker/Dockerfile.only-deps \
          --build-arg CHANNEL_MOUNT=tmp/conda-channel \
          --cache-from=type=gha \
          --cache-to=type=gha \
          .
          docker push ${{ env.IMAGE_TAG }}

  build-testable:
    runs-on: ubuntu-latest
    needs:
      - build-conda-channel
      - build-only-deps
    outputs:
      image-tag: ${{ steps.set-tag.outputs.image-tag }}
    steps:
      - uses: actions/checkout@v4
      - name: Download conda channel
        uses: actions/download-artifact@v4
        with:
          name: rattler-artifacts
          path: tmp/conda-channel
      - name: Log conda channel contents
        run: ls -lR tmp/conda-channel
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set testable image tag on env and output for downstream jobs
        id: set-tag
        run: |  # todo: change tag to :${{ dependency-files-hash }}-${{ commit-sha }}
          export NAME=wildlife-dynamics/ecoscope-workflows-testable
          export TAG=latest
          echo "IMAGE_TAG=ghcr.io/$NAME:$TAG" >> $GITHUB_ENV
          echo "image-tag=ghcr.io/$NAME:$TAG" >> $GITHUB_OUTPUT
      - name: Build testable container
        run: |
          docker buildx build \
          --tag ${{ env.IMAGE_TAG }} \
          --platform=linux/amd64 \
          --file docker/Dockerfile.base \
          --build-arg ONLY_DEPS_IMAGE_TAG=${{ needs.build-only-deps.outputs.image-tag }} \
          --build-arg CHANNEL_MOUNT=tmp/conda-channel \
          --cache-from=type=gha \
          --cache-to=type=gha \
          .
          docker push ${{ env.IMAGE_TAG }}

  local-e2e-test:
    runs-on: ubuntu-latest
    needs: build-testable
    steps:
      - name: Test worker container - sequential end-to-end
        shell: bash -leo pipefail {0}
        run: |
          docker run \
          -v `pwd`/tests:/opt/tests \
          -v `pwd`/examples:/opt/examples \
          ${{ needs.build-testable.outputs.image-tag }} \
          /env/bin/python -m pytest -v /opt/tests/test_examples.py \
          -k "end_to_end and sequential"

      - name: Test worker container - async end-to-end
        shell: bash -leo pipefail {0}
        run: |
          docker run \
          -v `pwd`/tests:/opt/tests \
          -v `pwd`/examples:/opt/examples \
          ${{ needs.build-testable.outputs.image-tag }} \
          /env/bin/python -m pytest -v /opt/tests/test_examples.py \
          -k "end_to_end and async"

  remote-e2e-test:
    runs-on: ubuntu-latest
    needs: build-testable
    steps:
      - uses: actions/checkout@v4
      - name: Setup build environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: rattler
          init-shell: bash
      - name: Build & install lithops
        shell: bash -leo pipefail {0}
        run: |
          micromamba install -c conda-forge rattler-build --yes
          rattler-build build --recipe .rattler-build/recipes/ps-mem.yaml --output-dir .rattler-build/artifacts --skip-existing=all
          rattler-build build --recipe .rattler-build/recipes/lithops.yaml  --output-dir .rattler-build/artifacts --skip-existing=all
          micromamba install -c file://$(pwd)/.rattler-build/artifacts lithops --yes

      - name: Google auth
        id: google-auth
        uses: google-github-actions/auth@v2
        with:
          # TODO: change to workload identity
          credentials_json: '${{ secrets.GCP_CLOUDRUN_LITHOPS_TESTING_SERVICE_ACCOUNT_KEY }}'

      - name: Set lithops runtime name on env
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            export COMMIT_SHA=${{ github.event.pull_request.head.sha }}
          else
            export COMMIT_SHA=${{ github.sha }}
          fi
          export SHORT_COMMIT_SHA=$(echo $COMMIT_SHA | cut -c1-7)
          echo "LITHOPS_RUNTIME_NAME=lithops-runtime-${{ github.event_name }}-$SHORT_COMMIT_SHA" >> $GITHUB_ENV

      - name: Create lithops config
        run: |
          cat <<EOF > .lithops-config.yaml
          lithops:
            backend: gcp_cloudrun
            storage: gcp_storage
            log_level: INFO
            data_limit: 500
          gcp:
            region: us-central1
          gcp_cloudrun:
            runtime: us.gcr.io/${{ steps.google-auth.outputs.project_id }}/${{ env.LITHOPS_RUNTIME_NAME }}
            runtime_cpu: 2
            runtime_memory: 1000
          EOF

      - name: Lithops build
        shell: bash -leo pipefail {0}
        run: |
          LITHOPS_CONFIG_FILE=.lithops-config.yaml \
          lithops runtime build -b gcp_cloudrun \
          -f docker/Dockerfile.worker \
          ${{ env.LITHOPS_RUNTIME_NAME }}

      - name: Lithops deploy
        shell: bash -leo pipefail {0}
        run: |
          LITHOPS_CONFIG_FILE=.lithops-config.yaml \
          lithops runtime deploy ${{ env.LITHOPS_RUNTIME_NAME }}

      - name: Test remote worker container - async end-to-end
        shell: bash -leo pipefail {0}
        run: |
          docker run \
          -v `pwd`/tests:/opt/tests \
          -v `pwd`/examples:/opt/examples \
          ecoscope-workflows-base /env/bin/python -m pytest -v /opt/tests/test_examples.py \
          -k "end_to_end and async"

      - name: Post Lithops deploy (teardown)
        if: always()  # always run teardown even if previous steps fail
        shell: bash -leo pipefail {0}
        run: |
          LITHOPS_CONFIG_FILE=.lithops-config.yaml \
          lithops runtime delete ${{ env.LITHOPS_RUNTIME_NAME }}
