name: Test Rattler Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: rattler
          init-shell: bash

      - name: Install build deps
        shell: bash -leo pipefail {0}
        run: |
          micromamba install -c conda-forge rattler-build PyYAML "python>=3.10" --yes

      - name: Build psmem
        shell: bash -leo pipefail {0}
        working-directory: deploy
        run: |
          rattler-build build --recipe rattler/ps-mem.yaml

      - name: Build lithops
        shell: bash -leo pipefail {0}
        working-directory: deploy
        run: |
          rattler-build build --recipe rattler/lithops.yaml

      - name: Build earthranger-client
        shell: bash -leo pipefail {0}
        working-directory: deploy
        run: |
          rattler-build build --recipe rattler/earthranger-client.yaml

      - name: Build lonboard
        shell: bash -leo pipefail {0}
        working-directory: deploy
        run: |
          rattler-build build --recipe rattler/lonboard.yaml

      - name: Build ecoscope-core
        shell: bash -leo pipefail {0}
        working-directory: deploy
        run: |
          rattler-build build --recipe rattler/ecoscope-core.yaml

      - name: Get correct COMMIT_SHA (regardless of event type)
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "COMMIT_SHA=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
          else
            echo "COMMIT_SHA=${{ github.sha }}" >> $GITHUB_ENV
          fi

      - name: Build ecoscope-workflows worker container at current commit
        shell: bash -leo pipefail {0}
        working-directory: deploy
        run: |
          chmod +x scripts/build_container_at_sha.sh
          ./scripts/build_container_at_sha.sh $COMMIT_SHA

      - name: Set short commit sha on env (this is the container tag)
        run: |
          echo "SHORT_COMMIT_SHA=$(echo $COMMIT_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Test worker container
        shell: bash -leo pipefail {0}
        run: |
          docker run \
          -v `pwd`/tests:/opt/tests \
          -v `pwd`/examples:/opt/examples \
          -e EARTHRANGER_SERVER=${{ secrets.EARTHRANGER_SERVER }} \
          -e EARTHRANGER_USERNAME=${{ secrets.EARTHRANGER_USERNAME }} \
          -e EARTHRANGER_PASSWORD=${{ secrets.EARTHRANGER_PASSWORD }} \
          $SHORT_COMMIT_SHA /bin/bash -c "\
          micromamba -n lithops-worker install -c conda-forge pytest --yes \
          && micromamba -n lithops-worker run pytest /opt/tests"
