name: Test Rattler Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: rattler
          init-shell: bash

      - name: Install build deps
        shell: bash -leo pipefail {0}
        run: |
          micromamba install -c conda-forge rattler-build --yes

      - name: Build psmem
        shell: bash -leo pipefail {0}
        working-directory: deploy
        run: |
          rattler-build build --recipe rattler/ps-mem.yaml

      - name: Build lithops
        shell: bash -leo pipefail {0}
        working-directory: deploy
        run: |
          rattler-build build --recipe rattler/lithops.yaml

      - name: Build earthranger-client
        shell: bash -leo pipefail {0}
        working-directory: deploy
        run: |
          rattler-build build --recipe rattler/earthranger-client.yaml

      - name: Build lonboard
        shell: bash -leo pipefail {0}
        working-directory: deploy
        run: |
          rattler-build build --recipe rattler/lonboard.yaml

      - name: Build ecoscope-core
        shell: bash -leo pipefail {0}
        working-directory: deploy
        run: |
          rattler-build build --recipe rattler/ecoscope-core.yaml

      # FIXME: make this run off of the current commit on the branch being tested
      - name: Build ecoscope-workflows
        shell: bash -leo pipefail {0}
        working-directory: deploy
        run: |
          rattler-build build --recipe rattler/ecoscope-workflows.yaml

      - name: Build worker container
        shell: bash -leo pipefail {0}
        working-directory: deploy
        run: |
          docker buildx build -t rattler-image -f Dockerfile.base .
